default_url_options:
  host: 'localhost:3000'

sorcery:
    # line_callback_url: 'https://localhost:3000/oauth/callback?provider=line'
    line_callback_url: 'https://e169-103-95-107-234.ngrok-free.app/oauth/callback?provider=line'