default_url_options:
  host: 'localhost:3000'

sorcery:
    # line_callback_url: 'https://localhost:3000/oauth/callback?provider=line'
    line_callback_url: 'https://1c66-2400-4153-1420-7200-1934-4740-8ae4-21da.ngrok-free.app/oauth/callback?provider=line&bot_prompt=aggressive'